### ISSUE TITLE
package.json repository attribute

### ISSUE THREAD

**Issue by grempe** [A11yWatch/intercom-next#11]
The NPM page for this code doesn't have a link to its source repository.

https://www.npmjs.com/package/next-intercom

I think if you add the repository attribute to `package.json` it would help developers discover and review the source code or file issues.

Thanks

**Comment by j-mendez** [comment]
@grempe thanks for the issue. This should be fixed now https://github.com/j-mendez/next-intercom/commit/0badb0e9425ddcd21730122244a742ebad279b4b.
