### ISSUE TITLE
onClick call back for intercom widget

### ISSUE THREAD

**Issue by Bhanukamax** [A11yWatch/intercom-next#16]
Hi, 

I see that currently there's no way to call a callback function when a user clicks on the intercom widget.
Is this something not possible with the current intercom library?

If it is possible, how hard is it to implement it for `next-intercom`?

**Comment by j-mendez** [comment]
Hi @Bhanukamax , you can use the Intercom('onShow') event to achieve this.

```ts
import { updateIntercom } from 'next-intercom'

updateIntercom('onShow', () => {
    console.log('composer opened!')
})

```
