### ISSUE TITLE
Is it possible to use for logged out users?

### ISSUE THREAD

**Issue by hronchetti** [A11yWatch/intercom-next#18]
I'm considering using this package for a SaaS marketing website. The marketing site will be outside the auth context of the product. 

After testing it seems the chat fails to load if no email or userId is passed, is there any way to use this package for logged-out users?

**Comment by j-mendez** [comment]
Hi @hronchetti, it should be possible and achieved by leaving the email empty as a falsey value (“”,false,null,undefined). I can take a look later today to see if anything has changed since the intercom version is not pinned.

**Comment by j-mendez** [comment]
@hronchetti I currently do not have an intercom acc to use to test.

**Comment by j-mendez** [comment]
Closing the PR since this is part of the identity verification setting https://developers.intercom.com/installing-intercom/docs/enable-identity-verification-on-your-web-product.
