### ISSUE TITLE
Intercom('Show')

### ISSUE THREAD

**Issue by ishaantilva** [A11yWatch/intercom-next#24]
Hi there,

Is there a way to achieve [this result](https://developers.intercom.com/installing-intercom/docs/intercom-javascript#intercomshow) through next-intercom? 

We're using loadIntercom() to add the user attributes but cannot use `Intercom('show')` since we're not using a <script> to add the messenger to the website.

**Comment by j-mendez** [comment]
Hi, you can use initIntercomWindow or  window.Intercom(“show”).
