### ISSUE TITLE
Rebooting intercom

### ISSUE THREAD

**Issue by paul-vd** [A11yWatch/intercom-next#4]
When my users log out i run `shutdownIntercom` which works as expected except i can not seem to reboot intercom? i tried re-initiating the `loadIntercom` but it does not seem to work. Should i maybe replace `showdownIntercom` with `updateIntercom` to remove any user data?

**Comment by j-mendez** [comment]
@PaulPCIO you should be able to use window.Intercom('boot') to re-open or simply use initIntercomWindow method.

**Comment by neilpoulin** [comment]
I'm also having this problem if i try to use the library methods. If i call straight up `window.Intercom('shtudown')` then `window.Intercom('boot', {app_id: 'MY_APP_ID'})` it works. I use typescript though so I had to do some configuration to get the Window type to work correctly:

```typescript
interface MyWindow extends Window {
    Intercom?: (event: string, options?: unknown | null) => void;
}


export const restartIntercom = () => {
    stopIntercom();
    bootIntercom();
};

export const stopIntercom = () => {
    const w = window as MyWindow;
    if (process.browser && window && w.Intercom) {
        w.Intercom('shutdown');
    }
};

export const bootIntercom = () => {
    const w = window as MyWindow;
    if (process.browser && window && w.Intercom) {
        w.Intercom('boot', { app_id: config.intercom.appId });
    }
};



```

**Comment by j-mendez** [comment]
Hello @Neilpoulin, I think it would make sense for this change something like a reboot command. If process.browser is removed this can be added in. The window method should be the feature detection.
